<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actual stock' => 'Aktuális készlet',
    'Add new incoming' => 'Új bevétel',
    'Add new outgoing' => 'Új kiadás',
    'All Items' => 'Mind',
    'Amount' => 'Mennyiség',
    'Are you sure you want to delete this item?' => 'Biztos benne, hogy törli ezt az elemet?',
    'Categories' => 'Kategóriák',
    'Category' => 'Kategória',
    'Comment' => 'Megjegyzés',
    'Create Category' => 'Új kategória',
    'Create Item' => 'Új munkadarab',
    'Create Incoming' => 'Új bevétel',
    'Create Outgoing' => 'Új kiadás',
    'Delete' => 'Törlés',
    'ID' => 'ID',
    'Incoming' => 'Bevétel',
    'Item' => 'Munkadarab',
    'Item name' => 'Munkadarab neve',
    'Items' => 'Munkadarabok',
    'Minimal stock' => 'Minimális készlet',
    'Only Low' => 'Alacsony készlet',
    'Outgoing' => 'Kiadás',
    'Reset' => 'Alaphelyzet',
    'Save' => 'Mentés',
    'Search' => 'Keresés',
    'Select Category' => 'Kategória választása',
    'The requested page does not exist.' => 'A kért oldal nem létezik.',
    'Update' => 'Szerkesztés',
    'Update Item' => 'Munkadarab szerkesztése',
    'Update Category' => 'Kategória szerkesztése',
    'Update Outgoing' => 'Kiadás szerkesztése',
    'Update Incoming' => 'Bevétel szerkesztése',
];
